CREATE TABLE Food (
    FoodID INT AUTO_INCREMENT PRIMARY KEY,
    Url VARCHAR(255),
    Label VARCHAR(255),
    Enerc_Kcal DECIMAL(10,2),
    Protein DECIMAL(10,2),
    Fat DECIMAL(10,2),
    Carbohydrate DECIMAL(10,2),
    Fiber DECIMAL(10,2),
    Category VARCHAR(255),
    Weight DECIMAL(10,2),
    Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
